DROP TABLE RESTAURANT;

CREATE TABLE RESTAURANT(
    RESTAURANT_ID NUMBER PRIMARY KEY,
    REGION VARCHAR2(256 CHAR),
    TYPE VARCHAR2(20 CHAR),
    MAIN_MENU VARCHAR2(1024 CHAR),
    NAME VARCHAR2(20 CHAR),
    ADDRESS VARCHAR2(1024 CHAR),
    PHONE_NUMBER VARCHAR2(1024 CHAR)
);

DROP SEQUENCE RESTAURANT_SEQ;
CREATE SEQUENCE RESTAURANT_SEQ;

--------------------------------------------------------------------------------

DROP TABLE RESORT;

CREATE TABLE RESORT(
    RESORT_ID NUMBER PRIMARY KEY,
    REGION VARCHAR2(256 CHAR),
    TYPE VARCHAR2(20 CHAR),
    NAME VARCHAR2(50 CHAR),
    ADDRESS VARCHAR2(1024 CHAR),
    ROOM VARCHAR2(50 CHAR),
    PHONE_NUMBER VARCHAR2(1024 CHAR)
);

DROP SEQUENCE RESORT_SEQ;
CREATE SEQUENCE RESORT_SEQ;

--------------------------------------------------------------------------------

DROP TABLE TOUR;

CREATE TABLE TOUR(
    TOUR_ID NUMBER PRIMARY KEY,
    LG_TYPE VARCHAR2(100 CHAR),
    MD_TYPE VARCHAR2(100 CHAR),
    SM_TYPE VARCHAR2(100 CHAR),
    REGION VARCHAR2(256 CHAR),
    LOCATION VARCHAR2(256 CHAR),
    NAME VARCHAR2(50 CHAR),
    ADDRESS VARCHAR2(1024 CHAR)
);

DROP SEQUENCE TOUR_SEQ;
CREATE SEQUENCE TOUR_SEQ;


--------------------------------------------------------------
- ø©«‡ ∞Ë»π

DROP TABLE PLAN;

CREATE TABLE PLAN(
    USER_ID VARCHAR2(50 CHAR),
    PLAN_ID NUMBER PRIMARY KEY,
    TITLE VARCHAR2(100 CHAR) NOT NULL,
    WRITER VARCHAR2(100 CHAR) NOT NULL,
    CONTENT VARCHAR2(1024 CHAR),
    REG_DATE DATE DEFAULT SYSDATE,
    UPDATE_DATE DATE DEFAULT SYSDATE
);

DROP SEQUENCE PLAN_SEQ;
CREATE SEQUENCE PLAN_SEQ;


-----------------------------------------------------------------

delete 
from plan
where user_id='polo';
