DROP TABLE GALLERY;

CREATE TABLE GALLERY(
    ID NUMBER PRIMARY KEY,
    TITLE VARCHAR2(256 CHAR),
    DESCRIPTION VARCHAR2(1024 CHAR),
    FILE_NAME VARCHAR2(256 CHAR),
    FILE_SIZE NUMBER,
    IMAGE BLOB,
    THUMB BLOB,
    REG_DATE DATE DEFAULT SYSDATE,
    UPDATE_DATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE GALLERY_SEQ;