SELECT LPAD(' ',(LEVEL-1)*4) || LAST_NAME
FROM HR.EMPLOYEES
START WITH MANAGER_ID IS NULL
CONNECT BY MANAGER_ID= PRIOR EMPLOYEE_ID
ORDER SIBLINGS BY HIRE_DATE;

SELECT LPAD(' ',(LEVEL-1)*4) || LAST_NAME,
    SYS_CONNECT_BY_PATH(LAST_NAME,'->')
FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID=50
START WITH MANAGER_ID = 100
CONNECT BY MANAGER_ID= PRIOR EMPLOYEE_ID
ORDER SIBLINGS BY HIRE_DATE;




----------------------------------------------------------------------------
-댓글 테이블 정의

DROP TABLE REPLY;
CREATE TABLE REPLY(
    REPLY_ID    NUMBER PRIMARY KEY,
    BOARD_ID    NUMBER,
    PARENT      NUMBER,
    PASSWORD    VARCHAR2(20) NOT NULL,
    WRITER      VARCHAR2(20) NOT NULL,
    CONTENT     VARCHAR2(1024),
    DELETED     NUMBER(1) DEFAULT(0),
    REG_DATE    DATE DEFAULT (SYSDATE),
    UPDATE_DATE DATE DEFAULT (SYSDATE),
    CONSTRAINT  F_REPLIES_BOARD FOREIGN KEY(BOARD_ID)
        REFERENCES BOARD(BOARD_ID),
    CONSTRAINT  F_REPLIES_MEMBER FOREIGN KEY(WRITER)
        REFERENCES  MEMBER(USER_ID)
);
DROP SEQUENCE REPLY_SEQ;
CREATE SEQUENCE REPLY_SEQ;